# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Cypress run
        uses: cypress-io/github-action@v1.16.1
        with:
          env: visualRegressionTracker='{"apiUrl":${{ secrets.VRT_API_URL }},"project":"VRT","apiKey":${{ secrets.VRT_API_KEY }},"branchName":"master","enableSoftAssert":false}'
