name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Setup Node.js environment
      uses: actions/setup-node@v1.4.2
    
    - name: Install npm dependencies
      run: npm ci
      
    - name: Unit tests
      run: npm run test:cov
    
    - name: Codecov
      uses: codecov/codecov-action@v1.0.11
